/**
 * Environment configuration for multi-environment parameter comparison.
 * Used by AdminParameters to fetch and display parameters from all environments.
 */

export type EnvironmentId = 'development' | 'staging' | 'production';

export interface EnvironmentConfig {
  id: EnvironmentId;
  label: string;
  supabaseUrl: string;
  anonKey: string;
  apiBaseUrl: string;
  badgeColor: string;
  icon: string;
}

// Standard local Supabase anon key (deterministic, generated by supabase start)
const LOCAL_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0';

const STAGING_URL = 'https://dqoybysbooxngrsxaekd.supabase.co';
const STAGING_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxb3lieXNib294bmdyc3hhZWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTc2OTYsImV4cCI6MjA3MjkzMzY5Nn0.tj87Iq5Me6weY5LKL8HMeyUJyfYDoozJZ6J3iD4QoiA';

const PRODUCTION_URL = 'https://tpsgnnrkwgvgnsktuicr.supabase.co';
const PRODUCTION_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwc2dubnJrd2d2Z25za3R1aWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1MDE2NDcsImV4cCI6MjA4NjA3NzY0N30.oSLIdSvLWWdHWWcMyJ3WR4zwsu1tCAbawdkIYnQqnVY';

const EDGE_FN_PATH = '/functions/v1/make-server-ce05600a';

export const ENVIRONMENTS: EnvironmentConfig[] = [
  {
    id: 'development',
    label: 'Development',
    supabaseUrl: 'http://127.0.0.1:54321',
    anonKey: LOCAL_ANON_KEY,
    apiBaseUrl: `http://127.0.0.1:54321${EDGE_FN_PATH}`,
    badgeColor: 'bg-blue-100 text-blue-700 border-blue-200',
    icon: '💻',
  },
  {
    id: 'staging',
    label: 'Staging',
    supabaseUrl: STAGING_URL,
    anonKey: STAGING_ANON_KEY,
    apiBaseUrl: `${STAGING_URL}${EDGE_FN_PATH}`,
    badgeColor: 'bg-amber-100 text-amber-700 border-amber-200',
    icon: '🧪',
  },
  {
    id: 'production',
    label: 'Production',
    supabaseUrl: PRODUCTION_URL,
    anonKey: PRODUCTION_ANON_KEY,
    apiBaseUrl: `${PRODUCTION_URL}${EDGE_FN_PATH}`,
    badgeColor: 'bg-green-100 text-green-700 border-green-200',
    icon: '🚀',
  },
];

export function getCurrentEnvironmentId(): EnvironmentId {
  const url = import.meta.env.VITE_SUPABASE_URL || '';
  if (url.includes('127.0.0.1') || url.includes('localhost')) return 'development';
  if (url.includes('dqoybysbooxngrsxaekd')) return 'staging';
  return 'production';
}

export function getCurrentEnvironment(): EnvironmentConfig {
  const id = getCurrentEnvironmentId();
  return ENVIRONMENTS.find(e => e.id === id)!;
}
